In [13]:
import numpy as np
import pandas as pd

In [14]:
city = pd.read_csv('cities_r2.csv')

In [20]:
city.info

<bound method DataFrame.info of      name_of_city  state_code      state_name  dist_code  population_total  \
0          Abohar           3          PUNJAB          9            145238
1        Achalpur          27     MAHARASHTRA          7            112293
2        Adilabad          28  ANDHRA PRADESH          1            117388
3       Adityapur          20       JHARKHAND         24            173988
4           Adoni          28  ANDHRA PRADESH         21            166537
..            ...         ...             ...        ...               ...
488  Vizianagaram          28  ANDHRA PRADESH         12            227533
489      Warangal          28  ANDHRA PRADESH          9            620116
490        Wardha          27     MAHARASHTRA          8            105543
491   Yamunanagar           6         HARYANA          3            216628
492      Yavatmal          27     MAHARASHTRA         14            116714

     population_male  population_female  0-6_population_total  \
0              76840              68398                 15870
1              58256              54037                 11810
2              59232              58156                 13103
3              91495              82493                 23042
4              82743              83794                 18406
..               ...                ...                   ...
488           111596             115937                 20487
489           310400             309716                 55392
490            53241              52302                  9754
491           115404             101224                 22905
492            58717              57997                 11081

     0-6_population_male  0-6_population_female  ...  literates_female  \
0                   8587                   7283  ...             44972
1                   6186                   5624  ...             43086
2                   6731                   6372  ...             37660
3                  12063                  10979  ...             54515
4                   9355                   9051  ...             45089
..                   ...                    ...  ...               ...
488                10495                   9992  ...             80306
489                28434                  26958  ...            217136
490                 5139                   4615  ...             43339
491                12556                  10349  ...             74255
492                 5894                   5187  ...             46561

     sex_ratio  child_sex_ratio  effective_literacy_rate_total  \
0          890              848                          79.86
1          928              909                          91.99
2          982              947                          80.51
3          902              910                          83.46
4         1013              968                          68.38
..         ...              ...                            ...
488       1039              952                          81.85
489        998              948                          84.16
490        982              898                          94.05
491        877              824                          85.91
492        988              880                          91.81

     effective_literacy_rate_male  effective_literacy_rate_female  \
0                           85.49                           73.59
1                           94.77                           89.00
2                           88.18                           72.73
3                           89.98                           76.23
4                           76.58                           60.33
..                            ...                             ...
488                         88.18                           75.80
489                         91.54                           76.79
490                         97.19                           90.88
491                         89.61                           81.71
492                         95.45                           88.17

                  location  total_graduates male_graduates  female_graduates
0    30.1452928,74.1993043            16287           8612              7675
1     21.257584,77.5086754             8863           5269              3594
2     19.0809075,79.560344            10565           6797              3768
3    22.7834741,86.1576889            19225          12189              7036
4    15.6322227,77.2728368            11902           7871              4031
..                     ...              ...            ...               ...
488  18.1066576,83.3955506            30656          19173             11483
489  17.9689008,79.5940544           109613          69507             40106
490   20.745319,78.6021946            19363          10645              8718
491  30.1290485,77.2673901            29803          14349             15454
492  20.3887937,78.1204073            13511           7397              6114

[493 rows x 22 columns]>

In [16]:
city.head()

,name_of_city,state_code,state_name,dist_code,population_total,population_male,population_female,0-6_population_total,0-6_population_male,0-6_population_female,...,literates_female,sex_ratio,child_sex_ratio,effective_literacy_rate_total,effective_literacy_rate_male,effective_literacy_rate_female,location,total_graduates,male_graduates,female_graduates
0,Abohar,3,PUNJAB,9,145238,76840,68398,15870,8587,7283,...,44972,890,848,79.86,85.49,73.59,"30.1452928,74.1993043",16287,8612,7675
1,Achalpur,27,MAHARASHTRA,7,112293,58256,54037,11810,6186,5624,...,43086,928,909,91.99,94.77,89.00,"21.257584,77.5086754",8863,5269,3594
2,Adilabad,28,ANDHRA PRADESH,1,117388,59232,58156,13103,6731,6372,...,37660,982,947,80.51,88.18,72.73,"19.0809075,79.560344",10565,6797,3768
3,Adityapur,20,JHARKHAND,24,173988,91495,82493,23042,12063,10979,...,54515,902,910,83.46,89.98,76.23,"22.7834741,86.1576889",19225,12189,7036
4,Adoni,28,ANDHRA PRADESH,21,166537,82743,83794,18406,9355,9051,...,45089,1013,968,68.38,76.58,60.33,"15.6322227,77.2728368",11902,7871,4031

In [17]:
city['name_of_city'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 493 entries, 0 to 492
Series name: name_of_city
Non-Null Count  Dtype
--------------  -----
493 non-null    object
dtypes: object(1)
memory usage: 4.0+ KB

In [18]:
city['name_of_city'].describe()

count            493
unique           492
top       Aurangabad
freq               2
Name: name_of_city, dtype: object

In [29]:
city.sort_values(["state_code","dist_code"], ascending = [1,1]) #sorting the valaue of state code in ascending order

,name_of_city,state_code,state_name,dist_code,population_total,population_male,population_female,0-6_population_total,0-6_population_male,0-6_population_female,...,literates_female,sex_ratio,child_sex_ratio,effective_literacy_rate_total,effective_literacy_rate_male,effective_literacy_rate_female,location,total_graduates,male_graduates,female_graduates
445,Srinagar,1,JAMMU & KASHMIR,10,1192792,631916,560876,148178,79293,68885,...,312526,888,869,70.98,77.61,63.52,"34.0836708,74.7972825",135783,75825,59958
30,Anantnag,1,JAMMU & KASHMIR,14,108505,56030,52475,18056,9633,8423,...,31817,937,874,78.95,85.33,72.23,"33.7311255,75.1487007",12666,7291,5375
231,Jammu,1,JAMMU & KASHMIR,21,503690,265346,238344,42655,23317,19338,...,187956,898,829,89.66,93.13,85.82,"32.7266016,74.8570259",121564,65587,55977
431,Shimla,2,HIMACHAL PRADESH,11,169758,93364,76394,13646,7221,6425,...,65313,818,890,94.67,95.75,93.35,"31.1048145,77.1734033",43353,23822,19531
66,Batala,3,PUNJAB,1,156400,82459,73941,14698,8028,6670,...,55037,897,831,85.49,88.81,81.81,"31.8183238,75.2070644",16436,8120,8316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,Kurichi,33,TAMIL NADU,31,125800,63033,62767,12092,6111,5981,...,49238,996,979,90.42,94.13,86.71,"11.5707716,77.6966143",13160,6926,6234
465,Tiruppur,33,TAMIL NADU,32,444543,227469,217074,45091,23039,22052,...,160710,954,957,87.67,92.69,82.41,"11.1085242,77.3410656",33358,18431,14927
357,Ozhukarai,34,PUDUCHERRY,2,300028,148154,151874,29214,14910,14304,...,117601,1025,959,90.20,95.06,85.48,"11.9475611,79.7793932",50682,28317,22365
378,Puducherry,34,PUDUCHERRY,2,241773,118205,123568,22412,11245,11167,...,95442,1045,993,89.29,93.88,84.91,"11.9138598,79.8144722",37830,21086,16744
376,Port Blair,35,ANDAMAN & NICOBAR ISLANDS,3,100608,53247,47361,9358,4852,4506,...,37000,889,929,89.76,92.79,86.34,"11.6233774,92.7264828",12420,6717,5703

In [38]:
city.loc[city["literates_female"] >1000000].sort_values(["literates_female"], ascending = [1])

,name_of_city,state_code,state_name,dist_code,population_total,population_male,population_female,0-6_population_total,0-6_population_male,0-6_population_female,...,literates_female,sex_ratio,child_sex_ratio,effective_literacy_rate_total,effective_literacy_rate_male,effective_literacy_rate_female,location,total_graduates,male_graduates,female_graduates
380,Pune,27,MAHARASHTRA,25,3115431,1602137,1513294,324572,171152,153420,...,1195486,945,896,91.61,95.13,87.91,"18.5204303,73.8567437",656508,349022,307486
449,Surat,24,GUJARAT,25,4462002,2538243,1923759,531522,293208,238314,...,1416640,758,813,89.03,92.76,84.05,"21.1702401,72.8310607",278795,160566,118229
274,Kolkata,19,WEST BENGAL,16,4486679,2362662,2124017,300052,155475,144577,...,1682088,899,930,87.14,89.08,84.98,"22.572646,88.363895",818476,461615,356861
119,Chennai,33,TAMIL NADU,2,4681087,2357633,2323454,418541,213084,205457,...,1845974,986,964,90.33,93.47,87.16,"13.0826802,80.2707184",879695,487428,392267
7,Ahmadabad,24,GUJARAT,7,5570585,2935869,2634716,589076,317917,271159,...,2004480,897,853,89.62,93.96,84.81,"23.022505,72.5713621",769858,435267,334591
184,Greater Hyderabad,28,ANDHRA PRADESH,99,6809970,3500802,3309168,725816,373794,352022,...,2359594,945,942,82.96,85.96,79.79,"17.3850,78.4867",1164149,685402,478747
72,Bengaluru,29,KARNATAKA,18,8425970,4401299,4024671,862493,444639,417854,...,3110983,914,940,89.59,92.63,86.25,"12.9716,77.5946",1591163,908363,682800
141,Delhi,7,NCT OF DELHI,99,11007835,5871362,5136473,1209275,647938,561337,...,3806615,875,866,87.60,91.44,83.20,"28.7041,77.1025",2221137,1210040,1011097
185,Greater Mumbai,27,MAHARASHTRA,99,12478447,6736815,5741632,1139146,599007,540139,...,4509812,852,902,90.28,93.32,86.70,"19.0760,72.8777",1802371,964964,837407